language: cpp
dist: bionic
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: CONFIG=Release
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: CONFIG=Debug
  - os: linux
    compiler: clang
    env: CONFIG=Release
#   - os: linux
#     compiler: clang
#     env: CONFIG=Debug
  - os: linux
    compiler: gcc
    env: CONFIG=Release
  - os: linux
    compiler: gcc
    env: CONFIG=Debug
#cache:
#  directories:
#    $HOME/deps-rel
#    $HOME/deps-dbg
script:
  - "git submodule update --init --recursive;"
  - "mkdir build;"
  - "cd build;"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_OSX_ARCHITECTURES=x86_64; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then cmake .. -DCMAKE_PREFIX_PATH=$INSTPRF -DCMAKE_BUILD_TYPE=${CONFIG}; fi"
  - "make all -j2"
# TODO need to sort out false-failures due to container/platform issues.
#  - "ctest -V"
sudo: false
addons:
  homebrew:
    update: true
    brewfile: true
  apt:
    # Details and approved sources are
    # from https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    #sources:
    # No extra sources needed on bionic
    packages:
    - libusb-1.0-0-dev
    - libboost-thread-dev
    - libboost-system-dev
    - libboost-date-time-dev
    - libboost-chrono-dev
    - libboost-program-options-dev
    - libboost-filesystem-dev
    - libopencv-dev
    - libjsoncpp-dev
    - libuvc-dev
